# Generated by Django 3.2.25 on 2025-09-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_class', models.CharField(blank=True, max_length=100, null=True)),
                ('navigation_status', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptionPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type_id', models.PositiveSmallIntegerField(help_text='0 = Free, 1 = Trial, 2 = Paid')),
                ('plan_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.PositiveSmallIntegerField(default=0, help_text='0 = Unpaid, 1 = Paid, 2 = Pending')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vidya_apis.users')),
            ],
            options={
                'db_table': 'user_subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_code', models.PositiveSmallIntegerField(help_text='0 = Student, 1 = Teacher, 2 = Admin, etc.')),
                ('role_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vidya_apis.users')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('usage_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vidya_apis.userrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vidya_apis.users')),
            ],
            options={
                'db_table': 'usage',
            },
        ),
    ]
